#!/bin/sh

export AARCH64_TOOLS_DIR=$HOME/work/apm/8.0.10-le/bin
export AARCH64_TOOL_PREFIX=aarch64-apm-linux-gnu-
export TOOLS_DIR=$HOME/work/Tools

if [ -z $1 ]; then
    make 2>&1 | tee bld
else
    make $1
fi
