#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: bf /path/to/inf"
    exit 1
fi

conf_file=Conf/target.txt
if [ ! -f $conf_file ]; then
    echo "File $conf_file not found, aborting"
    exit 1
fi

target=$(cat $conf_file|grep TARGET|rev|cut -f1 --delimiter=' '|rev)
if [ -z $target ]; then
    echo "Cannot find target description in $conf_file"
    exit 1
fi

if [ "$target" == "DEBUG" ]; then
    EXTERNAL_CC_FLAGS="-D PI_SPECIFICATION_VERSION=0x10028 -D EFI_SPECIFICATION_VERSION=0x2003C -Os -DEFI_DEBUG"
else
    EXTERNAL_CC_FLAGS="-D PI_SPECIFICATION_VERSION=0x10028 -D EFI_SPECIFICATION_VERSION=0x2003C -Os -DMDEPKG_NDEBUG"
fi

WORKSPACE=$(pwd)
EFI_SOURCE=$(pwd)
EDK_TOOLS_PATH=$HOME/work/Tools
ASL_COMPILER=iasl6
CONFIGURATION_DIR=AmiPkg/Configuration/
export WORKSPACE
export EFI_SOURCE
export EDK_TOOLS_PATH
export ASL_COMPILER
export PATH=$PATH:$HOME/work/Tools:$HOME/work/Tools/Bin/Linux64
export EXTERNAL_CC_FLAGS
export CONFIGURATION_DIR

mv $conf_file $conf_file.save
cat $conf_file.save | sed -e "/TOOL_CHAIN_.*/d" > $conf_file
echo "TOOL_CHAIN_CONF = /home/artex2000/work/FakeTools/FAKE_DEF.txt" >> $conf_file
echo "TOOL_CHAIN_TAG = FAKE" >> $conf_file

OUT_FILE=$(pwd)/compile_commands.json
export OUT_FILE

if [ -f $OUT_FILE ]; then
    sed -i '$ d' $OUT_FILE
else
    echo "[" > $OUT_FILE
fi

/home/artex2000/work/Tools/Bin/Linux64/build -m $1
echo "]" >> $OUT_FILE

mv $conf_file.save $conf_file
